// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package pgdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Kategori struct {
	IDKategori   int32  `json:"id_kategori"`
	NamaKategori string `json:"nama_kategori"`
}

type Produk struct {
	Id         int32            `json:"id_produk"`
	NamaProduk string           `json:"nama_produk"`
	Harga      pgtype.Numeric   `json:"harga"`
	KategoriID int64            `json:"kategori_id"`
	StatusID   int64            `json:"status_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Status struct {
	IDStatus   int32  `json:"id_status"`
	NamaStatus string `json:"nama_status"`
}
